version: '3'
services:
  flask-app:
    image: barmalini/grade-submission-portal:1.0.0
    container_name: flask-app
    ports:
      - "5001:5001"
    environment:
      - GRADE_SERVICE_HOST=node-server
    depends_on:
      - node-server

  node-server:
    image: barmalini/grade-submission-api:1.0.0
    container_name: node-server
    ports:
      - "3000:3000"


